### ISSUE TITLE
Sprint 1 - Testing

### ISSUE THREAD

**Issue by Thomaslongwell** [hbarton2/cscd350-f24-SWAGCRAFT#26]
We need tests that will be functional even with later sprints of the project, more details will be spoken about during the meeting 10/18 at 5:30 pm

**Comment by hackerbgone** [comment]
If possible I'd like to lay claim on testing Fields, Methods, or Interface.

**Comment by hackerbgone** [comment]
Completed unit testing towards Fields, Interface, and Relationships branch. Also made better error handling for Fields.
