### ISSUE TITLE
Add Type to Relationships

### ISSUE THREAD

**Issue by Thomaslongwell** [hbarton2/cscd350-f24-SWAGCRAFT#36]
Given I am in the program in the main menu, When I type or select the command to add relationships I will be able to assign a type (Aggregation, Composition, Generalization, and Realization) to the relationship, then when I display the relationships the relationship and type will be displayed

**Comment by Thomaslongwell** [comment]
this will also need a "CHANGE TYPE" method

**Comment by afudge1** [comment]
Done!
