### ISSUE TITLE
Plan GUI Code to Adhere to MVC

### ISSUE THREAD

**Issue by Thomaslongwell** [hbarton2/cscd350-f24-SWAGCRAFT#40]
Any future code in the project will need to adhere to the MVC model

**Comment by hackerbgone** [comment]
Working currently to move my handler and helper functions for my GUI into the controller class.

**Comment by hackerbgone** [comment]
Going into sprint 3 with everything fleshed out. I will make an effort to move my helper/action functions into controller class.

**Comment by hackerbgone** [comment]
GUI Adheres to OOP MVC Format, using controller calls.
