### ISSUE TITLE
Sprint 3 - Undo and Redo in GUI Implementing MOMENTO pattern

### ISSUE THREAD

**Issue by Thomaslongwell** [hbarton2/cscd350-f24-SWAGCRAFT#61]
For undo and redo memento design pattern 
Two stacks: history(undo) and redo stack 
Ex: add class goes in undo opposite (remove class) redo (pop undo and put into redo stack) 
https://refactoring.guru/design-patterns/memento

**Comment by Thomaslongwell** [comment]
we will need to ask if the CLI requires this functionality before programming it specific to the GUI

**Comment by fatimanadam** [comment]
**Other Thoughts**
- Implement undo/redo for specific actions like adding/removing class boxes, resizing, and connecting/disconnecting arrows.
- Ensure that undo/redo stacks are cleared or reset when a new diagram is loaded or a new project is started.
- Test for edge cases, such as undoing multiple complex changes (e.g., dragging, resizing, deleting).
