### ISSUE TITLE
GUI Layout Optimization

### ISSUE THREAD

**Issue by fatimanadam** [hbarton2/cscd350-f24-SWAGCRAFT#83]
Ensure the GUI layout is intuitive and elements (such as buttons, menus, and windows) are in locations that make sense to the user.
- Ensure that actions performed in the CLI reflect immediately in the GUI and vice versa.
- Test both environments to ensure consistency in functionality across the GUI and CLI, particularly for undo/redo.

**Comment by hackerbgone** [comment]
completed
