### ISSUE TITLE
Save and Load Class Box Locations

### ISSUE THREAD

**Issue by fatimanadam** [hbarton2/cscd350-f24-SWAGCRAFT#86]
- Implement functionality to save the positions of class boxes to a file.
- Ensure that the class box positions are restored when the project is loaded.
- Define the file format (JSON) used to save class box locations.
- Implement error handling for corrupted or incompatible save files.
- Ensure that loaded class diagrams retain all their relationships, positions, and any other attributes like color or labels.

**Comment by hackerbgone** [comment]
Early implementation save/load class position frames, updating logic today to create persistence.

**Comment by hackerbgone** [comment]
completed and committed to dev branch.
