### ISSUE TITLE
Implement Resizable Relationship Arrows

### ISSUE THREAD

**Issue by fatimanadam** [hbarton2/cscd350-f24-SWAGCRAFT#87]
- Ensure relationship arrows resize dynamically when class boxes are moved or resized.
- Ensure that arrows never disappear, even when resizing.
- Create constraints for the minimum and maximum size of arrows to ensure they don’t become too small or large.
- Test the behavior of relationship arrows when multiple class boxes are moved simultaneously.

**Comment by hackerbgone** [comment]
Never brought this to fruition in terms of arrow resizing, and in fact made it a functionality so where if the class boxes are too close together at a certain threshold, the relationship lines between the two classes don't render, as to avoid graphical glitches. This being said I am happy with the draw relationship implementation.
