### ISSUE TITLE
Implement Draggable Class Boxes

### ISSUE THREAD

**Issue by fatimanadam** [hbarton2/cscd350-f24-SWAGCRAFT#88]
- Make class boxes draggable within the GUI.
- Ensure that box positions are saved when the user saves the project and reloaded in the same positions.
- Test edge cases such as dragging a class box outside the visible window or to a corner of the GUI.
- Ensure that dragging operations snap to a grid (if necessary) to align boxes neatly.

**Comment by hackerbgone** [comment]
Resolved. Closing.
